// This file was generated by Prisma and expects `prisma` and `dotenv` to be installed.
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx ts-node src/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
