ALTER TABLE "Category"
ADD COLUMN "nameEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Category"
ADD COLUMN "descriptionEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Product"
ADD COLUMN "nameEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Product"
ADD COLUMN "descriptionEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Product"
ADD COLUMN "advantagesEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Product"
ADD COLUMN "compositionEn" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Product"
ADD COLUMN "applicationEn" TEXT NOT NULL DEFAULT '';
